### PR TITLE
Use correct currency when fetching prices

### PR DESCRIPTION
**Pull request by jschlyter**

### CODE REVIEW

**Comment by jschlyter** [comment]
Already addressed in #41

**Comment by kipe** [comment]
Merging this rather than #41, as this is targeting the correct branch and doesn't have extra commits.

**Comment by kipe** [comment]
@jschlyter Can you remove the 204 commit from this branch. I'd rather keep the issues separate.

**Comment by jschlyter** [comment]
Replaced by #45

**Pull request closed without merging**
