### PR TITLE
Page lookup helpers

### LINKED ISSUE #17: Wrong currency returned
The Nordpool API will return all answers in EUR unless an area is specified at the same time. This currently results in multiple issues. Since the library selects currency first (`elspot.Prices`) and area second (`hourly`), the currency will always be returned in EUR (the most common one).

This can be replicated via the Nordpool web UI:

- Visit https://www.nordpoolgroup.com/Market-data1/Dayahead/Area-Prices/ALL1/Hourly
- Confirm that EUR is the only acceptable currency
- Select country SE
- Discover that multiple currencies are now available

Further investigation shows that the pages defined at https://github.com/kipe/nordpool/blob/master/nordpool/elspot.py#L11 does not provide data in other currencies than EUR. Using specific pages (e.g., 29 for SE3) returns data in multiple currencies. The area to page map is most likely subject to change of course.

### PR DESCRIPTION
**Pull request by jschlyter**
First step to resolve #17 is to find the correct page given area and data type.

# Example

```
from nordpool import elspot

spot = elspot.Prices(currency="SEK")
page = spot.get_page(country="SE", data_type=elspot.NordpoolDataType.HOURLY)
data = spot.fetch(page, end_date=date.today(), areas=["SE1", "SE2", "SE3", "SE4"])
```

### CODE REVIEW

**Comment by jschlyter** [comment]
```
from nordpool import elspot

spot = elspot.Prices(currency="SEK")
page = spot.get_page(country="SE", data_type=elspot.NordpoolDataset.HOURLY)
data = spot.fetch(page, end_date=date.today(), areas=["SE1", "SE2", "SE3", "SE4"])
```

**Comment by Hellowlol** [comment]
Why +1 why set the correct page index in the dict?

**Comment by jschlyter** [comment]
> Why +1 why set the correct page index in the dict?

The hourly/daily/weekly/monthly/yearly pages has an offset from the base page of 1…5. In order to maintain backward compability I choosed to calculate it backwards. I agree it is a bit confusing, so I've changed to more obvious logic in c012f3875f1157fa2b4d55998b7abbb9fef316af.

**Comment by kipe** [comment]
I'll see if this could be done without changes to the API, without too much spaghetti. It would be a lot nicer way to implement it.
Although we'll see how long this API even stays, Nordpool has been hinting on making an official API for non-commercial use.

**Comment by jschlyter** [comment]
> I'll see if this could be done without changes to the API, without too much spaghetti. It would be a lot nicer way to implement it.
> Although we'll see how long this API even stays, Nordpool has been hinting on making an official API for non-commercial use.

I'd prefer if the API would not change, but with this code it is at least possible to adopt. Happy to see it solved without the extra call to `get_page()`.

**Comment by kipe** [comment]
Closing for now, as it seems like Nordpool has fixed the issue in their end.

**Pull request closed without merging**
